### ISSUE TITLE
Article date missing margin getting close to article text

### ISSUE THREAD

**Issue by nepo-dev** [Edearth/edearth.github.io#10]
# Problem
Article date is missing some margin. As a consequence, the text from the article is getting awfully close to it.

<img width="211" alt="Screenshot 2022-08-09 at 16 11 29" src="https://user-images.githubusercontent.com/8767085/183671299-d40e49a8-fce7-4d91-9d03-812df5f8c561.png">

# Fix

Add:
```css
.article-date {
    margin-left: 20px;
}
```
